######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 16 09:38:19 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/y/l/yly/Desktop/EC535/project/. .

# Input
HEADERS += custom.h
SOURCES += custom.cpp main.cpp
